// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/drivers": {
            "get": {
                "description": "Busca a lista de todos motoristas e seus veiculos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Motoristas"
                ],
                "summary": "lista motoristas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Driver"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to list all",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Este endpoint permite adicionar um novo motorista e seu veiculo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Motoristas"
                ],
                "summary": "cria novo motorista e veiculo",
                "parameters": [
                    {
                        "description": "Numero de CNH",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Nome do motorista",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Número da plata",
                        "name": "license_plate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Modelo do veiculo",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Driver"
                        }
                    },
                    "400": {
                        "description": "failed to bind json",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to store",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/drivers/{cnh}": {
            "get": {
                "description": "Este endpoint permite buscar dados e veiculos de um motorista identificado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Motoristas"
                ],
                "summary": "buscar um motorista",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Número de CNH",
                        "name": "cnh",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Driver"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Este endpoint permite alterar dados do motorista",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Motoristas"
                ],
                "summary": "edita motorista",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Número de CNH",
                        "name": "cnh",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nome do motorista",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Driver"
                            }
                        }
                    },
                    "400": {
                        "description": "failed to bind json",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to update",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Este endpoint remove dados do motorista e seus veiculos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Motoristas"
                ],
                "summary": "remove motorista",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Número de CNH",
                        "name": "cnh",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "failed to delete",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/drivers/{cnh}/vehicles/{license_plate}": {
            "get": {
                "description": "Este endpoint busca um veiculo especifico de um motorista através de sua placa",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Veiculos"
                ],
                "summary": "recupera veiculo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Número de CNH",
                        "name": "cnh",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Número da Placa do Veiculo",
                        "name": "license_plate",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Driver"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Este endpoint permite editar dados de um veiculo especifico de um motorista",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Veiculos"
                ],
                "summary": "edita veiculo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Número de CNH",
                        "name": "cnh",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Número da Placa do Veiculo",
                        "name": "license_plate",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Modelo do veiculo",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Driver"
                        }
                    },
                    "400": {
                        "description": "failed to bind json",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to update",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Este endpoint remove veiculo especifico de um motorista",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Veiculos"
                ],
                "summary": "remove veiculo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Número de CNH",
                        "name": "cnh",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Número da Placa do Veiculo",
                        "name": "license_plate",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to delete",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health Check"
                ],
                "summary": "ping example",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.Driver": {
            "type": "object",
            "properties": {
                "cnh": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "license_plate": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
